### ISSUE TITLE
Online Help for MakeSchreierTreeShallow  is not complete

### ISSUE THREAD

**Issue by klauslux** [gap-system/orb#11]
The Online help for MakeSchreierTreeShallow does not mention  the orbit object
that is the argument to MakeSchreierTreeShallow has to have a "log".

**Comment by fingolfin** [comment]
Indeed. If I understand things right, there is no reason for that -- well, except that with a log, `AddGeneratorsToOrbit` is more efficient, so this could speed-up the code.
So, we could just remove this requirement from `MakeSchreierTreeShallow`. And perhaps print a warning (via Info, say at Info level 1?) if `MakeSchreierTreeShallow` is called for an orbit without log.

@klauslux Do you have any "real world" examples where you know the results so we can test this? There seem to be no tests for this function right now, so I am a bit wary about making changes to it.

**Comment by fingolfin** [comment]
Of course another point of view would be to say that using `MakeSchreierTreeShallow` only makes sense with a log, because only then it is efficient -- I cannot judge that myself, though, since I know no actual examples (but I'll try to see if I can make up some ;-)

**Comment by fingolfin** [comment]
A quick test shows that `MakeSchreierTreeShallow` needs the `o!.orbind` member which is only set when logging is enabled. So I guess the documentation needs to be updated. And perhaps a `MakeSchreierTreeShallow` method for non-log orbits could be added, which prints a helpful error.
