### ISSUE TITLE
Incoherent license information

### ISSUE THREAD

**Issue by jamesjer** [gap-system/orb#14]
Most of the project claims to be released under the GPL version 3 or any later version.  But:
- the file GPL contains the text of the GPL version 2, not 3.
- src/orb.c says it is released under the GPL version 2.  The "or any later version" clause is missing, so it is released under exactly version 2:

Therefore, the entire project cannot be released under the GPL version 2 because of the version 3 or later files, and it also cannot be released under the GPL version 3 because of src/orb.c.

**Comment by markuspf** [comment]
Dear @jamesjer ,

could you have a look whether pull-request #15 clears up your concerns wrt licensing?

Cheers

**Comment by jamesjer** [comment]
Sorry for the delay.  Yes, that does clear up my concerns.  Thank you for addressing them so promptly.  Regards, Jerry.

**Comment by fingolfin** [comment]
Resolved in 6ca004d4f08d12fb4bfead136320885512e8102d

**Comment by markuspf** [comment]
For completeness, @ChrisJefferson noted that GPL3 is incompatible with GPL2, which means that now GAP itself has a license incompatible with orb.
